### ISSUE TITLE
get_active_users返回相同用户多次

### ISSUE THREAD

**Issue by yjw1029** [USTCSoftware2018/Backend-Legacy#33] opened 2018-10-12 02:15 UTC
现在返回结果如下
```json
{
 "success": true,
 "data": {
  "count": 13,
  "next": null,
  "previous": null,
  "results": [
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   },
   {
    "id": 1,
    "avatar_url": "https://www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?s=328&r=g&d=identicon",
    "username": "test",
    "description": "description"
   }
  ]
 },
 "status": 200
}
```

**Comment by ksqsf** [comment] 2018-10-12 02:19
Duplicate of #31 and it's already fixed.

**Closed by ksqsf** 2018-10-12 02:19 UTC
